version: '3'

services:
  db:
    image: postgres:13
    restart: always
    container_name: procrastination_db
    volumes:
      - ./database/alembic_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - procrastination_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: procrastination_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ultimate_procrastination
    command: ["postgres", "-c", "log_statement=all"]

  procrastination_bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: procrastination_bot
    restart: "no"
    networks:
      - procrastination_network
    volumes:
      - ./config.json:/ultimate_procrastination/config.json
    depends_on:
      - "procrastination_web"
    environment:
      - PYTHONUNBUFFERED=1
    command:
      - "python3"
      - "bot/main.py"

  procrastination_web:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: procrastination_web
    restart: "no"
    networks:
      - procrastination_network
    depends_on:
      - "db"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
       - ./config.json:/ultimate_procrastination/config.json
    entrypoint: ./wait-for-port-availability.sh -h db -p 5432 -t 0 --
    command:
      - "uvicorn"
      - "api.main:start_app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"

networks:
  procrastination_network:
    name: procrastination_network