"""add amount of likes colomn to titles

Revision ID: 19edbc6a1713
Revises: cbaf731dfbac
Create Date: 2021-07-28 23:07:39.117110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19edbc6a1713'
down_revision = 'cbaf731dfbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('amount_of_likes', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'amount_of_likes')
    # ### end Alembic commands ###
