"""create new table with category names and foreing keys to it

Revision ID: 2fc7aa4d249f
Revises: 19edbc6a1713
Create Date: 2021-07-31 22:55:25.350100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc7aa4d249f'
down_revision = '19edbc6a1713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_foreign_key(None, 'ratings', 'categories', ['category_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'titles', 'categories', ['title_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'titles', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_table('categories')
    # ### end Alembic commands ###
