"""renaming

Revision ID: 833742647001
Revises: 1d1f25510179
Create Date: 2021-06-28 22:45:26.025096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833742647001'
down_revision = '1d1f25510179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rating_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rating_types_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rating_types_pkey')
    )
    op.drop_table('ratings')
    # ### end Alembic commands ###
