"""titles in one table rating table rework

Revision ID: b7563307136e
Revises: 833742647001
Create Date: 2021-07-08 21:24:14.061957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7563307136e'
down_revision = '833742647001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('title_name', sa.String(length=40), nullable=False),
    sa.Column('title_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('it_titles')
    op.drop_table('physics_titles')
    op.drop_table('history_titles')
    op.drop_table('chemistry_titles')
    op.drop_table('biology_titles')
    op.add_column('ratings', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_column('ratings', 'subject_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ratings', 'category_id')
    op.create_table('biology_titles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='biology_titles_pkey')
    )
    op.create_table('chemistry_titles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chemistry_titles_pkey')
    )
    op.create_table('history_titles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='history_titles_pkey')
    )
    op.create_table('physics_titles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='physics_titles_pkey')
    )
    op.create_table('it_titles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='it_titles_pkey')
    )
    op.drop_table('titles')
    # ### end Alembic commands ###
