"""rename colons, add email field

Revision ID: b8bfe837dd9d
Revises: b7563307136e
Create Date: 2021-07-19 23:48:43.339282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bfe837dd9d'
down_revision = 'b7563307136e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('category_type_id', sa.Integer(), nullable=False))
    op.drop_column('ratings', 'category_id')
    op.add_column('titles', sa.Column('title_type_id', sa.Integer(), nullable=False))
    op.add_column('titles', sa.Column('amount_of_views', sa.Integer(), nullable=False))
    op.drop_column('titles', 'title_id')
    op.add_column('users', sa.Column('email', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.add_column('titles', sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('titles', 'amount_of_views')
    op.drop_column('titles', 'title_type_id')
    op.add_column('ratings', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('ratings', 'category_type_id')
    # ### end Alembic commands ###
